<center><h1>Lista de transacciones</h1></center>
<div class="row">

<nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="<?php echo APP_URL."transacciones/index"; ?>">Money Tracking</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <!-- left navigation links -->
      <ul class="navbar-nav mr-auto">

        <!-- active navigation link -->
        <li class="nav-item active">
          <a class="nav-link" href="<?php echo APP_URL."transacciones/index"; ?>">Transacciones
            <span class="sr-only">(current)</span>
          </a>
        </li>

        <!-- regular navigation link -->
        <li class="nav-item">
          <a class="nav-link" href="<?php echo APP_URL."categorias/index"; ?>">Categorías</a>
        </li>

        <!-- more navigation links -->
           <li class="nav-item">
          <a class="nav-link" href="<?php echo APP_URL."cuentas/index"; ?>">Cuentas</a>
        </li>


      </ul>

      <!-- right navigation link -->
    </div>
  </div>
</nav>
        <br><br>
        <div class="col-md-12 text-left">
            <a href="<?php echo APP_URL."categorias/agregar"; ?>">
                <button type="button" class="btn btn-primary"> 
                    <i class="fa fa-plus"></i>
                    Agregar nueva categoría
                </button>
            </a>
        </div>
        <br><br>
        <div class="table-responsive centered">
            <table class="table table-hover table-bordered table-condensed responsive-table">
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Acción</th>
                </tr>
                <?php foreach ($this->categorias as $categoria): ?>
                    <tr>
                        <td><?php echo $categoria["id"]; ?></td>
                        <td><?php echo $categoria["name"]; ?></td>
                        <td> <a href="<?php echo APP_URL."categorias/editar/".$categoria["id"]; ?>"><i class="small material-icons">edit</i></a>
                             <a href="<?php echo APP_URL."categorias/eliminar/".$categoria["id"]; ?>" class="confirmation"><i class="small material-icons">delete</i></a>
                    </tr>
                <?php endforeach; ?>

            </table>
        </div>
    </div>

